name: CI/CD pipeline for Testing and Linting

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

env:
  cache-name: cache-node-modules

jobs:
  lint-code:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "development"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache NPM Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

  run-tests:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    needs: lint-code
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "test"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache NPM Dependencies
        uses: actions/cache@v3.3.2
        with:
          path: ~/.npm
          key: ${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ env.cache-name }}-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
